name: Feature CI

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt -mem 2048 test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          scoverage needs and update before this works on spark3
#      - name: Coverage Report
#        run: sbt coverageReport
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          fail_ci_if_error: true